server:
  port: 9090
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            username: root
            password: password
            authentication-database: admin
            database: spring
    redis:
      host: localhost
      port: 6379
    cache:
        redis:
            cache-null-values: false
            time-to-live: 40000
        type: redis
